export const POLICY_RULES = {
  ACCRUAL_FREQUENCY: {
    MONTHLY: "MONTHLY",
    QUARTERLY: "QUARTERLY",
    ANNUAL: "ANNUAL",
  },

  COUNTING_RULES: {
    INCLUDE_WEEKENDS: "INCLUDE_WEEKENDS",
    EXCLUDE_WEEKENDS: "EXCLUDE_WEEKENDS",
    INCLUDE_HOLIDAYS: "INCLUDE_HOLIDAYS",
    EXCLUDE_HOLIDAYS: "EXCLUDE_HOLIDAYS",
  },

  CARRY_FORWARD: {
    NONE: "NONE",
    LIMITED: "LIMITED",
    UNLIMITED: "UNLIMITED",
  },
};
